### ISSUE TITLE
why not to use GoogleWebRTC

### ISSUE THREAD

**Issue by 1395881288** [amirali-asvadi/Janus-Video-Room-Swift#1]
in the podfile file
pod "WebRTC"
why not to use 
pod "GoogleWebRTC"

thanks.

**Comment by amirali-asvadi** [comment]
@1395881288 
You are right,
"WebRTC" is deprecated now, and we should use "GoogleWebRTC".
Thanks for informing me and I appreciate it if you create a pull request to update the pod file.
